#!/usr/bin/env python3
"""Package pre-built polyclav binaries into a manylinux Python wheel.

go-to-wheel can't be used here: it forces CGO_ENABLED=0 and cross-compiles,
but polyclav is a cgo binary linking a Rust staticlib + PipeWire/ALSA/lilv.
So we build the binary natively (see .github/workflows/publish.yml) and
package it ourselves.

The binaries go in `<dist>.data/scripts/`, which pip/uv install straight into
the environment's bin/ — so `uvx polyclav` runs the native binary directly,
no Python shim. The wheel is dynamically linked: it depends on the user's
system PipeWire/ALSA/lilv (FHS-standard locations, resolved by SONAME via
ldconfig). It is tagged manylinux (a glibc-baseline promise) but is NOT
auditwheel-self-contained — by design (no bundling, no static linking).

Usage:
  build_wheel.py --version 0.1.0 \
      --platform-tag manylinux_2_35_x86_64 \
      --binary dist/polyclav --binary dist/polyclav-components \
      --readme README.md --output-dir dist
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import zipfile
from pathlib import Path

NAME = "polyclav"
SUMMARY = "Live-piano host: MIDI keyboard -> soundfont/plugin synthesis -> system audio (Linux PipeWire / macOS CoreAudio)"
AUTHOR = "Matthew Schulkind"
URL = "https://github.com/mschulkind-oss/polyclav"
LICENSE = "Apache-2.0"

# POSIX sh launcher shipped in place of each binary with --exec-wrapper.
# The binary is dynamically linked against the distro's PipeWire/ALSA/lilv;
# when one is missing, the raw binary dies with "error while loading shared
# libraries" before any polyclav code runs (so `polyclav doctor` cannot
# report it — see cmd/polyclav/doctor.go's requiredLibsFooter). This wrapper
# turns that loader error into the fix: ~20 ms of ldd, once per start,
# skipped entirely where ldd doesn't exist.
WRAPPER_TEMPLATE = """\
#!/bin/sh
# polyclav launcher -- generated by scripts/build_wheel.py; do not edit.
BIN="$(dirname "$0")/__NAME__.bin"
if command -v ldd >/dev/null 2>&1; then
    missing=$(ldd "$BIN" 2>&1 | grep -F 'not found')
    if [ -n "$missing" ]; then
        echo "polyclav: this system is missing libraries polyclav needs:" >&2
        echo >&2
        printf '%s\\n' "$missing" >&2
        cat >&2 <<'EOF'

Install them from your distro:
    Debian/Ubuntu: sudo apt install pipewire libasound2 liblilv-0-0
    Fedora:        sudo dnf install pipewire alsa-lib lilv
    Arch:          sudo pacman -S pipewire alsa-lib lilv

A "GLIBC_x.y ... not found" line instead means this distro's glibc is older
than the release binary's baseline -- build from source:
    https://github.com/mschulkind-oss/polyclav#build-from-source
EOF
        exit 127
    fi
fi
exec "$BIN" "$@"
"""


def _record_line(arcname: str, data: bytes) -> str:
    digest = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=").decode()
    return f"{arcname},sha256={digest},{len(data)}"


def build(
    version: str,
    platform_tag: str,
    binaries: list[Path],
    readme: Path,
    out_dir: Path,
    exec_wrapper: bool = False,
) -> Path:
    dist_info = f"{NAME}-{version}.dist-info"
    data_scripts = f"{NAME}-{version}.data/scripts"

    long_desc = readme.read_text(encoding="utf-8") if readme and readme.exists() else SUMMARY

    metadata = "\n".join(
        [
            "Metadata-Version: 2.1",
            f"Name: {NAME}",
            f"Version: {version}",
            f"Summary: {SUMMARY}",
            f"Author: {AUTHOR}",
            f"License: {LICENSE}",
            f"Project-URL: Homepage, {URL}",
            "Description-Content-Type: text/markdown",
            "Classifier: Operating System :: POSIX :: Linux",
            "Classifier: Operating System :: MacOS",
            "Classifier: License :: OSI Approved :: Apache Software License",
            "Classifier: Topic :: Multimedia :: Sound/Audio :: MIDI",
            "Requires-Python: >=3.8",
            "",
            long_desc,
        ]
    )

    wheel_meta = "\n".join(
        [
            "Wheel-Version: 1.0",
            "Generator: polyclav-build_wheel",
            "Root-Is-Purelib: false",
            f"Tag: py3-none-{platform_tag}",
            "",
        ]
    )

    # (arcname, data, is_executable)
    entries: list[tuple[str, bytes, bool]] = []
    for b in binaries:
        if exec_wrapper:
            entries.append((f"{data_scripts}/{b.name}.bin", b.read_bytes(), True))
            wrapper = WRAPPER_TEMPLATE.replace("__NAME__", b.name).encode("utf-8")
            entries.append((f"{data_scripts}/{b.name}", wrapper, True))
        else:
            entries.append((f"{data_scripts}/{b.name}", b.read_bytes(), True))
    entries.append((f"{dist_info}/METADATA", metadata.encode("utf-8"), False))
    entries.append((f"{dist_info}/WHEEL", wheel_meta.encode("utf-8"), False))

    record_lines = [_record_line(arc, data) for arc, data, _ in entries]
    record_lines.append(f"{dist_info}/RECORD,,")
    record = ("\n".join(record_lines) + "\n").encode("utf-8")
    entries.append((f"{dist_info}/RECORD", record, False))

    out_dir.mkdir(parents=True, exist_ok=True)
    wheel_path = out_dir / f"{NAME}-{version}-py3-none-{platform_tag}.whl"
    with zipfile.ZipFile(wheel_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for arc, data, is_exec in entries:
            info = zipfile.ZipInfo(arc)
            # rwxr-xr-x for binaries, rw-r--r-- for metadata; high 16 bits = mode.
            info.external_attr = (0o755 if is_exec else 0o644) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, data)

    return wheel_path


def main() -> None:
    ap = argparse.ArgumentParser(description="Package polyclav binaries into a manylinux wheel.")
    ap.add_argument("--version", required=True)
    ap.add_argument("--platform-tag", required=True, help="e.g. manylinux_2_35_x86_64")
    ap.add_argument("--binary", action="append", dest="binaries", required=True, type=Path)
    ap.add_argument("--readme", type=Path, default=Path("README.md"))
    ap.add_argument("--output-dir", type=Path, default=Path("dist"))
    ap.add_argument(
        "--exec-wrapper",
        action="store_true",
        help="ship each binary as NAME.bin behind a sh launcher that diagnoses "
        "missing system libraries (Linux wheels; the raw loader error is "
        "unactionable and precedes any polyclav code)",
    )
    args = ap.parse_args()

    for b in args.binaries:
        if not b.exists():
            raise SystemExit(f"binary not found: {b}")

    wheel = build(
        args.version,
        args.platform_tag,
        args.binaries,
        args.readme,
        args.output_dir,
        exec_wrapper=args.exec_wrapper,
    )
    print(f"built {wheel} ({wheel.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
